apiVersion: "deployment-flipper.io/v1"
kind: DeploymentFlipper
metadata:
  name: my-flipper
spec:
  intervalSeconds: 60
  logLevel: info
  include:
    namespaces:
      - microservice-a
      - microservice-b
  exclude:
    namespaces:
      - kube-system
      - istio-system
      - argocd
      - prometheus
      - grafana
    enableDefaults: false
  image: hjcian/my-awesome-image
