apiVersion: v1
kind: ConfigMap
metadata:
  name: env-cm
  namespace: default
data:
  key1: env-cm-value1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envfrom-cm
  namespace: default
data:
  key1: envfrom-cm-value1
  key2: envfrom-cm-value2
---
apiVersion: v1
kind: Secret
metadata:
  name: env-sc
  namespace: default
stringData:
  key1: env-sc-value1
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment-flipper.watch: "true"
  name: deployment-flipper-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: deployment-flipper-demo
  template:
    metadata:
      labels:
        app: deployment-flipper-demo
    spec:
      containers:
        - name: deployment-flipper-demo
          image: alpine:latest
          command: ["ash", "-c", "--"]
          args:
            [
              'while true; echo "cm-env=$(env-cm) cm-enffrom1=$key1 cm-enffrom2=$key2 cm-enffrom3=$key3"; do sleep 1; done;',
            ]
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: env-cm
              valueFrom:
                configMapKeyRef:
                  name: env-cm
                  key: key1
            - name: env-sc
              valueFrom:
                secretKeyRef:
                  name: env-sc
                  key: key1
          envFrom:
            - configMapRef:
                name: envfrom-cm
